---
- name: install apache
  yum:
    name: httpd
    state: latest
- name: start apache server
  service:
    name: httpd
    state: started
- name: copy sample test file
  copy:
    src: index.html
    dest: /var/www/html/

