---
- name: install php
  yum:
     name: php
     state: latest
- name: starting apache server
  service:
     name: httpd
     state: started
- name: copy phpinfo file
  copy:
      src: phpinfo.php
      dest: /var/www/html/
  notify: restart apache server
